openapi: 3.1.0
info:
  description: Authorization APIs for connect
  title: Connect Auth
  version: 1.0.0
servers:
- description: Production
  url: https://api.eka.care
- description: Stage/Sandbox
  url: https://api.dev.eka.care
paths:
  /connect-auth/v1/account/login:
    post:
      description: Authorization APIs to get access and refresh token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountLoginRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountLoginResponse'
          description: OK
      security:
      - authApiKey: []
  /connect-auth/v1/account/refresh:
    post:
      description: Get new Authorization token using the refresh token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRefreshRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountRefreshResponse'
          description: OK
      security:
      - authApiKey: []

  /connect-auth/v1/oidc-client/{client_id}/login:
    get:
      description: OIDC Client Login
      parameters:
        - $ref: '#/components/parameters/client_id'

      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OidcLoginResponse'
          description: OK
      tags:
      - Auth (OIDC Token APIs)
  /connect-auth/v1/oidc-client/{client_id}/refresh:
    post:
      description: Auth Refresh
      parameters:
        - $ref: '#/components/parameters/client_id'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcOIDCRefreshRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelsUserSession'
          description: OK
      security:
      - authApiKey: []
      tags:
      - Auth (OIDC Token APIs)
  /connect-auth/v1/oidc-client/{client_id}/verify:
    post:
      description: Auth Verify and Eka Token
      parameters:
        - $ref: '#/components/parameters/client_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcVerifyRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelsOIDCCallbackResponse'
          description: OK
      security:
      - authApiKey: []
      tags:
      - Auth (OIDC Token APIs)
  
components:
  schemas:
    AccountLoginRequest:
      properties:
        api_key:
          description: Optional, API Token for additional scopes
          type:
          - "null"
          - string
        client_id:
          type: string
        client_secret:
          type: string
      type: object
    AccountLoginResponse:
      properties:
        access_token:
          type: string
        expires_in:
          description: Access token expiry in seconds
          type: integer
        refresh_expires_in:
          description: Refresh token expiry in seconds
          type: integer
        refresh_token:
          type: string
      type: object
    AccountRefreshRequest:
      properties:
        refresh_token:
          type: string
      type: object
    AccountRefreshResponse:
      properties:
        access_token:
          type: string
        expires_in:
          description: Access token expiry in seconds
          type: integer
        refresh_expires_in:
          description: Refresh token expiry in seconds
          type: integer
        refresh_token:
          type: string
      type: object
    OidcLoginResponse:
      properties:
        oauth_state:
          type: string
        redirect_url:
          type: string
      type: object
    OidcOIDCRefreshRequest:
      properties:
        refresh_token:
          type: string
      type: object
    ModelsUserSession:
      properties:
        access_token:
          type: string
        expires_at:
          format: date-time
          type: string
        id_token:
          type: string
        refresh_token:
          type: string
        user_info:
          $ref: '#/components/schemas/ModelsUserInfo'
      type: object
    ModelsUserInfo:
      properties:
        department:
          type: string
        doctor_id:
          type: string
        guid:
          type: string
        name:
          type: string
        sub:
          type: string
      type: object
    OidcVerifyRequest:
      properties:
        code:
          type: string
        id_token:
          type: string
        token:
          type: string
      type: object
    ModelsOIDCCallbackResponse:
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        redirect_url:
          type: string
        refresh_token:
          type: string
        refresh_token_expires_in:
          type: integer
      type: object
    GenericError:
      properties:
        code:
          type: integer
        error:
          type: string
      type: object

  parameters:
    client_id:
      name: client_id
      in: path
      required: true
      schema:
        type: string