openapi: 3.1.0
info:
  description: Authorization APIs for connect
  title: Connect Auth
  version: 1.0.0
servers:
- description: Production
  url: https://api.eka.care
- description: Stage/Sandbox
  url: https://api.dev.eka.care
paths:
  /connect-auth/v1/account/login:
    post:
      description: Authorization APIs to get access and refresh token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountLoginRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountLoginResponse'
          description: OK
      security:
      - authApiKey: []
  /connect-auth/v1/account/refresh:
    post:
      description: Get new Authorization token using the refresh token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRefreshRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountRefreshResponse'
          description: OK
      security:
      - authApiKey: []
components:
  schemas:
    AccountLoginRequest:
      properties:
        client_id:
          type: string
        client_secret:
          type: string
      type: object
    AccountLoginResponse:
      properties:
        access_token:
          type: string
        expires_in:
          description: Access token expiry in seconds
          type: integer
        refresh_expires_in:
          description: Refresh token expiry in seconds
          type: integer
        refresh_token:
          type: string
      type: object
    AccountRefreshRequest:
      properties:
        refresh_token:
          type: string
      type: object
    AccountRefreshResponse:
      properties:
        access_token:
          type: string
        expires_at:
          description: Access token expiry in seconds
          type: integer
        refresh_expires_at:
          description: Refresh token expiry in seconds
          type: integer
        refresh_token:
          type: string
      type: object
    GenericError:
      properties:
        code:
          type: integer
        error:
          type: string
      type: object
