openapi: 3.0.3  # Changed from 3.1.0 to comply with the required pattern
info:
  description: Authorization APIs for connect
  title: Eka Developer APIs
  version: 1.0.0
servers:
- description: Production
  url: https://api.eka.care
- description: Stage/Sandbox
  url: https://api.dev.eka.care
paths:
  /connect-auth/v1/account/login:
    post:
      description: Authorization APIs to get access and refresh token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountConnectLoginRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConnectLoginResponse'
          description: OK
      tags:
      - Connect APIs

  /connect-auth/v1/account/refresh:
    post:
      description: Get new Authorization token using the refresh token
      deprecated: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountConnectRefreshRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConnectRefreshResponse'
          description: OK
      tags:
      - Connect APIs
  /connect-auth/v1/account/refresh-token:
    post:
      description: Get new Authorization token using the refresh token
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: Bearer <access_token>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountConnectRefreshRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConnectRefreshResponse'
          description: OK
      tags:
      - Connect APIs
  
  /connect-auth/v1/oidc-client/{client_id}/refresh:
    post:
      description: Connect Client Auth Refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcRefreshPhrRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OidcVerifyPhrResponse'
          description: OK
      tags:
      - Auth (OIDC Token APIs)
  /connect-auth/v1/oidc-client/{client_id}/verify:
    post:
      description: Connect Client Auth Verify and Eka Token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcVerifyPhrRequest'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenapiGenericError'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OidcVerifyPhrResponse'
          description: OK
      tags:
      - Auth (OIDC Token APIs)
components:
  schemas:
    AccountConnectLoginRequest:
      properties:
        api_key:
          description: Optional, API Token for business id
          type: string
        client_id:
          type: string
        client_secret:
          type: string
        user_token:
          description: Optional, User token for user id
          type: string
      required:
        - client_id
        - client_secret
      type: object
    AccountConnectLoginResponse:
      properties:
        access_token:
          type: string
        expires_in:
          description: Access token expiry in seconds
          type: integer
        refresh_expires_in:
          description: Refresh token expiry in seconds
          type: integer
        refresh_token:
          type: string
      type: object
    AccountConnectRefreshRequest:
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
      required:
        - refresh_token
      type: object
    AccountConnectRefreshResponse:
      properties:
        access_token:
          type: string
        expires_in:
          description: Access token expiry in seconds
          type: integer
        refresh_expires_in:
          description: Refresh token expiry in seconds
          type: integer
        refresh_token:
          type: string
      type: object
    OidcRefreshPhrRequest:
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
      required:
        - refresh_token
      type: object
    OidcVerifyPhrRequest:
      properties:
        id_token:
          type: string
      required:
        - id_token
      type: object
    OidcVerifyPhrResponse:
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        redirect_url:
          type: string
        refresh_token:
          type: string
        refresh_token_expires_in:
          type: integer
      type: object
    OpenapiGenericError:
      properties:
        code:
          type: integer
        error:
          type: string
      type: object
  securitySchemes:  # Added security scheme definition
    authApiKey:
      type: apiKey
      name: Authorization  # Example header name; adjust as needed
      in: header
tags:
- description: APIs used for connect Authentication exposed through api.eka.care
  name: Connect APIs
- description: Apis to login to eka using partner's JWT token
  name: Auth (OIDC Token APIs)
x-tagGroups:
- name: Connect
  tags:
  - Connect APIs
  - Connect Internal
  - Auth (OIDC Token APIs)
