openapi: 3.0.3
info:
  title: Assessment APIs
  version: 1.0.0
servers:
  - url: https://api.eka.care

paths:
  /assessments/continue/:
    post:
      tags:
        - Assessments > Continue
      summary: Continue the assessment
      description: >-
        This API is used to continue the assessment. It accepts answer in the request body and returns the next question of the assessment.
        <Tip>Call this API multiple times until progress reaches 100%</Tip>
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                response:
                  qid: 0
                  respid:
                    id: 47258974-a65c-11eb-8d02-1e003a340630
                    choice: p
              description: >-
                The request body must contain the response to the question.
                The format should be:

                ```json

                {
                  "response": {
                    "qid": question_id (integer) from the previous response,
                    "respid": {
                      "id": "id of the option selected from previous response",
                      "choice": "choice selected from previous response"
                    }
                  }
                }

                ```

      parameters:
        - name: auth
          in: header
          required: True
          description: >-
            The auth token of the user. It is used to authenticate the user.
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJiX2lkIjoiMTIzNDU2IiwiY2xpZW50X2lkIjoiNzg5MCIsImV4dHJhX2ZpZWxkIjoiZXh0cmFfZmllbGRfZGF0YSJ9.q9KzBI6f4l3OyM_EkB5Quq0l9EEMFh5JS-fx3F_PHUM
        - name: Content-Type
          in: header
          description: >-
            The content type of the request. It is used to determine the type of data being sent.
          schema:
            type: string
          example: application/json
        - name: hash
          in: path
          required: True
          description: >-
            The conversation id of the assessment. It is used to identify the assessment.
          schema:
            type: string
          example: sn_2952355823833

      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Mon, 12 Aug 2024 07:41:05 GMT
            Server:
              schema:
                type: number
                example: WSGIServer/0.2 CPython/3.9.17
            Content-Type:
              schema:
                type: string
                example: application/json
            Vary:
              schema:
                type: string
                example: Accept, Cookie, origin
            Allow:
              schema:
                type: string
                example: POST, OPTIONS
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Length:
              schema:
                type: integer
                example: '51'
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Referrer-Policy:
              schema:
                type: string
                example: same-origin
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
          content:
            application/json:
              schema:
                type: object
              example:
                questions:
                - id: 1
                  text: Select all the symptoms you are experiencing
                  comp: I-MULT
                  tip: Select all option(s) that are applicable to you.
                  resp:
                  - id: s_b87e7437-1305-4973-b7f7-7b07f51fb80e
                    label: Red skin rash
                  - id: s_473b48a4-a65c-11eb-8d02-1e003a340630
                    label: Throat pain
                  - id: s_4720607a-a65c-11eb-8d02-1e003a340630
                    label: Headache
                  - id: s_477a119c-a65c-11eb-8d02-1e003a340630
                    label: Stuffy or blocked nose
                  - id: s_34410c44-b416-11eb-8c69-1e003a340631
                    label: Skin rash
                  - id: nota
                    label: None of the above
                progress: 7.69
                is_mandantory: true
                success: true
