openapi: 3.0.1
info:
  title: Health Repository API
  description: API for retrieving health records from Eka Care
  version: 1.0.0
servers:
  - url: https://health-repo.dev.eka.care/api/v1
paths:
  /fhir/retrieve:
    get:
      summary: Retrieve health records
      description: Retrieve a health record based on the given identifier, hip_id, and health_id.
      parameters:
        - name: identifier
          in: query
          required: true
          description: The unique identifier for the health record.
          schema:
            type: string
        - name: hip_id
          in: query
          required: true
          description: The HIP (Health Information Provider) ID.
          schema:
            type: string
        - name: health_id
          in: query
          required: true
          description: The health ID associated with the record.
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of health records.
          content:
            application/json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: Bundle
                  type:
                    type: string
                    example: document
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                        relation:
                          type: string
                  entry:
                    type: array
                    items:
                      type: object
                      properties:
                        resource:
                          type: object
                          properties:
                            author:
                              type: array
                              items:
                                type: object
                                properties:
                                  reference:
                                    type: string
                            date:
                              type: string
                              format: date-time
                            extension:
                              type: array
                              items:
                                type: object
                                properties:
                                  url:
                                    type: string
                                  valueString:
                                    type: string
                            id:
                              type: string
                            identifier:
                              type: object
                              properties:
                                system:
                                  type: string
                                value:
                                  type: string
                            meta:
                              type: object
                              properties:
                                lastUpdated:
                                  type: string
                                  format: date-time
                            resourceType:
                              type: string
                            section:
                              type: array
                              items:
                                type: object
                                properties:
                                  entry:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        reference:
                                          type: string
                                  title:
                                    type: string
                            status:
                              type: string
                            subject:
                              type: object
                              properties:
                                reference:
                                  type: string
                            title:
                              type: string
                            type:
                              type: object
                              properties:
                                text:
                                  type: string
                  id:
                    type: string
                  meta:
                    type: object
                    properties:
                      versionId:
                        type: string
                      lastUpdated:
                        type: string
                        format: date-time
                      profile:
                        type: array
                        items:
                          type: string
                      security:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                            display:
                              type: string
                            system:
                              type: string
                  identifier:
                    type: object
                    properties:
                      system:
                        type: string
                      value:
                        type: string
                  timestamp:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized. Invalid or missing authentication.
      security:
        - apikeyAuth: []
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: auth
