openapi: 3.1.0
info:
   title: MCP Eka Assist API
   description: Eka Assist documentation
   version: 1.0.0
   contact:
      name: Nikhil
      url: https://eka.care/
      email: nikhil.kasukurthi@eka.care
tags:
-  name: protocols
-  name: medications
paths:
   /eka-mcp/protocols/v1/search:
      post:
         summary: Search Protocols
         description: This endpoint returns pages from the protocols based on the
            query, publishers and tag.
         tags:
         - protocols
         parameters: []
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ProtocolList.a9993e3'
            '500':
               description: Internal Server Error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
            '403':
               description: Forbidden
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/QueryProtocols.b6c8896'
   /eka-mcp/protocols/v1/tags:
      get:
         summary: Get all Tags
         description: This endpoint returns the complete list of tags that are supported
            through search
         tags:
         - protocols
         parameters: []
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/TagList.a9993e3'
            '500':
               description: Internal Server Error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
            '403':
               description: Forbidden
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
   /eka-mcp/protocols/v1/publishers/tag:
      get:
         summary: Get Publishers by Tag
         description: This endpoint returns a list of all protocols publishers for
            given tag.
         tags:
         - protocols
         parameters:
         -  name: tag
            in: query
            schema:
               default: null
               description: The tag/condition for which the publisher is being fetched
               title: Tag
               type: string
            required: false
            description: The tag/condition for which the publisher is being fetched
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ProtocolPublishers.e57b7a5'
            '500':
               description: Internal Server Error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
            '403':
               description: Forbidden
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
   /eka-mcp/medications/v1/search:
      get:
         summary: Search Medications
         description: 'This endpoint returns suggested/similar drugs from the Eka
            medical database for the given parameters - drug name, generics, form
            or volume used by server.


            Suggestions are ranked based on similarity and also popularity (custom
            eka metric) of the medicine'
         tags:
         - medications
         parameters:
         -  name: drug_name
            in: query
            schema:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The segmented branded name of the medicine like Glim 1mg
               title: Drug Name
            required: false
            description: The segmented branded name of the medicine like Glim 1mg
         -  name: form
            in: query
            schema:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The form of the medicine like Tablet, Syrup
               title: Form
            required: false
            description: The form of the medicine like Tablet, Syrup
         -  name: generic_names
            in: query
            schema:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The generic name of the medicine like 'Glimeperide', 'Metformin'.
                  In case of compound generics, pass the name only with comma separated
                  like Glimeperide,Metformin
               title: Generic Names
            required: false
            description: The generic name of the medicine like 'Glimeperide', 'Metformin'.
               In case of compound generics, pass the name only with comma separated
               like Glimeperide,Metformin
         -  name: volumes
            in: query
            schema:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The volume of the drug name or generic composition like
                  '650','1000','500'
               title: Volumes
            required: false
            description: The volume of the drug name or generic composition like '650','1000','500'
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/MedicationList.a9993e3'
            '500':
               description: Internal Server Error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
            '403':
               description: Forbidden
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
   /eka-mcp/medications/v1/interaction:
      post:
         summary: Check Drugs Interactions
         description: 'This endpoint is used to check if given the list of drugs interact
            with each other. It check drugs interaction on the basis of generics composition.


            The interactions can be of any of the given categories: x,a,b,c,d or not
            have any interactions.'
         tags:
         - medications
         parameters:
         -  name: drug_names
            in: query
            schema:
               default: null
               description: 'List of drug names to check for interactions. Eg: [''Bencid
                  tablet'', ''Fluvir 75Mg capsule'']'
               items:
                  type: string
               title: Drug Names
               type: array
            required: false
            description: 'List of drug names to check for interactions. Eg: [''Bencid
               tablet'', ''Fluvir 75Mg capsule'']'
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Interaction.e57b7a5'
            '500':
               description: Internal Server Error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
            '403':
               description: Forbidden
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/GenericErr.82b01e4'
components:
   schemas:
      TagList.a9993e3:
         items:
            $ref: '#/components/schemas/TagList.a9993e3.Tag'
         title: TagList
         type: array
      GenericErr.82b01e4:
         properties:
            error:
               title: Error
               type: string
         required:
         - error
         title: GenericErr
         type: object
      ValidationError.6a07bef:
         title: ValidationError
         description: Model of a validation error response.
         type: array
         items:
            $ref: '#/components/schemas/ValidationError.6a07bef.ValidationErrorElement'
      QueryProtocols.b6c8896:
         properties:
            queries:
               description: List of non overlapping distinct queries to search for
                  protocols
               items:
                  $ref: '#/components/schemas/QueryProtocols.b6c8896.Protocol'
               title: Queries
               type: array
         required:
         - queries
         title: QueryProtocols
         type: object
      ProtocolList.a9993e3:
         items:
            $ref: '#/components/schemas/ProtocolList.a9993e3.Protocol'
         title: ProtocolList
         type: array
      ProtocolPublisher.b6c8896:
         properties:
            tag:
               default: null
               description: The tag/condition for which the publisher is being fetched
               title: Tag
               type: string
         title: ProtocolPublisher
         type: object
      ProtocolPublishers.e57b7a5:
         items:
            type: string
         title: ProtocolPublishers
         type: array
      MedicationUnderstanding.b6c8896:
         properties:
            drug_name:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The segmented branded name of the medicine like Glim 1mg
               title: Drug Name
            form:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The form of the medicine like Tablet, Syrup
               title: Form
            generic_names:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The generic name of the medicine like 'Glimeperide', 'Metformin'.
                  In case of compound generics, pass the name only with comma separated
                  like Glimeperide,Metformin
               title: Generic Names
            volumes:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               description: The volume of the drug name or generic composition like
                  '650','1000','500'
               title: Volumes
         title: MedicationUnderstanding
         type: object
      MedicationList.a9993e3:
         items:
            $ref: '#/components/schemas/MedicationList.a9993e3.Medication'
         title: MedicationList
         type: array
      MedicationInteraction.b6c8896:
         properties:
            drug_names:
               default: null
               description: 'List of drug names to check for interactions. Eg: [''Bencid
                  tablet'', ''Fluvir 75Mg capsule'']'
               items:
                  type: string
               title: Drug Names
               type: array
         title: MedicationInteraction
         type: object
      Interaction.e57b7a5:
         properties:
            a:
               anyOf:
               -  items:
                     items:
                        type: string
                     type: array
                  type: array
               -  type: 'null'
               default: null
               title: A
            b:
               anyOf:
               -  items:
                     items:
                        type: string
                     type: array
                  type: array
               -  type: 'null'
               default: null
               title: B
            c:
               anyOf:
               -  items:
                     items:
                        type: string
                     type: array
                  type: array
               -  type: 'null'
               default: null
               title: C
            d:
               anyOf:
               -  items:
                     items:
                        type: string
                     type: array
                  type: array
               -  type: 'null'
               default: null
               title: D
            x:
               anyOf:
               -  items:
                     items:
                        type: string
                     type: array
                  type: array
               -  type: 'null'
               default: null
               title: X
         title: Interaction
         type: object
      TagList.a9993e3.Tag:
         properties:
            tag_id:
               title: Tag Id
               type: string
            text:
               title: Text
               type: string
            detail:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               title: Detail
         required:
         - tag_id
         - text
         title: Tag
         type: object
      ValidationError.6a07bef.ValidationErrorElement:
         title: ValidationErrorElement
         description: Model of a validation error response element.
         type: object
         properties:
            loc:
               title: Missing field name
               type: array
               items:
                  type: string
            msg:
               title: Error message
               type: string
            type:
               title: Error type
               type: string
            ctx:
               title: Error context
               type: object
         required:
         - loc
         - msg
         - type
      QueryProtocols.b6c8896.Protocol:
         properties:
            query:
               description: Concise and exact sentence to search. Do not use when,
                  where, how, etc.
               title: Query
               type: string
            tag:
               description: The tag/condition basis which the protocols database should
                  be filtered
               title: Tag
               type: string
            publisher:
               description: The name of the publisher. Cannot be assumed unless specified
                  in the query by the user or selected from output of get_protocol_publishers
               title: Publisher
               type: string
         required:
         - query
         - tag
         - publisher
         title: Protocol
         type: object
      ProtocolList.a9993e3.Protocol:
         properties:
            url:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               title: Url
            source_url:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               title: Source Url
            type:
               anyOf:
               -  enum:
                  - image
                  - pdf
                  type: string
               -  type: 'null'
               default: null
               title: Type
            author:
               anyOf:
               -  type: string
               -  type: 'null'
               default: null
               title: Author
            publication_year:
               anyOf:
               -  type: integer
               -  type: 'null'
               default: null
               title: Publication Year
            conditions:
               anyOf:
               -  items:
                     type: string
                  type: array
               -  type: 'null'
               default: null
               title: Conditions
         title: Protocol
         type: object
      MedicationList.a9993e3.Medication:
         properties:
            name:
               title: Name
               type: string
            generic_name:
               anyOf:
               -  type: string
               -  type: 'null'
               title: Generic Name
            manufacturer_name:
               anyOf:
               -  type: string
               -  type: 'null'
               title: Manufacturer Name
            product_type:
               anyOf:
               -  type: string
               -  type: 'null'
               title: Product Type
         required:
         - name
         - generic_name
         - manufacturer_name
         - product_type
         title: Medication
         type: object
   securitySchemes:
      BearerAuth:
         type: http
         scheme: bearer
         bearerFormat: JWT
         description: Enter JWT token
servers:
-  url: https://api.dev.eka.care
   description: Staging Server
-  url: https://api.eka.care
   description: Prod Server
security:
-  BearerAuth: []
