openapi: 3.1.0
info:
  title: Transaction Status API
  version: 1.0.0
servers:
  - url: https://{{partner_host}}
paths:
  /registered_url_for_appointment_events:
    post:
      tags:
        - Appointment Webhooks
      summary: Appointment Events
      description: >-

        When an appointment is created/modified or completed, a webhook event is sent to registered
        webhooks with details about the appointment, including the appointment
        ID, status, doctor ID, patient ID, and event type.


        **Field Definitions**


        • **event**: string - The type of resource for which event is generated. For appointments, this
        will be `appointment`.


        • **data**: object - Contains detailed information about the appointment
        event.


        • **appointment_id**: string - Unique identifier for the appointment.


        • **doctor_id**: string - Unique identifier for the doctor.


        • **patient_id**: string - Unique identifier for the patient.


        • **status**: string - Status of the appointment. Possible values can be 
        
          - "BK" (Booked),
        
          - "OG" (Ongoing),
        
          - "CM" (Completed with Prescription),
        
          - "CMNP" (Completed without Prescription),
        
          - "CN" (Cancelled).
        
        
        • **action**: string - Current action for the appointment. Possible values can be 

            - created
        
            - modified
        
            - completed

        • **partner_meta**: key value pair specified by `partner` while creating appointment.  


        • **timestamp**: string (ISO 8601) - The date and time when the event
        occurred.


        • **custom_attibutes**: complete set of custom attributes(inclusing tags and labels) defined against this appointment.
        occurred.


        **Example Webhook Request**


        **Endpoint:**
        [https://your-registered-webhook-url.com](https://your-registered-webhook-url.com)


        **Method:** POST
      operationId: AppointmentWebhook
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              required:
                - event
                - event_time
                - timestamp
                - client_id
                - business_id
                - data
              properties:
                event:
                  type: string
                  example: "appointment.created"
                  description: "Type of event"
                event_time:
                  type: integer
                  example: 1730189586
                  description: "Event occured timestamp"
                timestamp:
                  type: integer
                  example: 1730189586
                  description: "Timestamp of the event"
                client_id:
                  type: string
                  example: "{{business_id}}"
                  description: "Client ID for the appointment"
                business_id:
                  type: string
                  example: "{{business_id}}"
                  description: "Business ID for the appointment"
                data:
                  type: object
                  required:
                    - appointment_id
                    - partner_appointment_id
                    - doctor_id
                    - patient_id
                    - clinic_id
                    - status
                    - action
                    - created_at
                    - modified_at
                  properties:
                    appointment_id:
                      type: string
                      example: "{{appointment_id}}"
                      description: "Unique appointment ID"
                    partner_appointment_id:
                      type: string
                      example: "{{partner_appointment_id}}"
                      description: "Partner's appointment ID"
                    doctor_id:
                      type: string
                      example: "{{doctor_id}}"
                      description: "Identifier for the doctor in Eka"
                    partner_doctor_id:
                      type: string
                      example: "{{partner_doctor_id}}"
                      description: "Identifier for the partner’s doctor"
                    patient_id:
                      type: string
                      example: "{{patient_id}}"
                      description: "Identifier for the patient in Eka"
                    partner_patient_id:
                      type: string
                      example: "{{partner_patient_id}}"
                      description: "Identifier for the partner’s patient"
                    clinic_id:
                      type: integer
                      example: "{{clinic_id}}"
                      description: "Identifier for the clinic in Eka"
                    partner_clinic_id:
                      type: string
                      example: "{{partner_clinic_id}}"
                      description: "Identifier for the partner’s clinic"
                    status:
                      type: string
                      example: "BK"
                      description: "Status of the appointment"
                    action:
                      type: string
                      example: "created"
                      description: "Action performed"
                    created_at:
                      type: integer
                      example: 1730189586
                      description: "Creation timestamp"
                    modified_at:
                      type: integer
                      example: 1730189586
                      description: "Modification timestamp"
                    custom_attributes:
                      type: object
                      properties:
                        label:
                          type: array
                          items:
                            type: string
                          example: ["vital_submitted"]
                      description: "Custom attributes for the event"
                    partner_meta:
                      type: object
                      properties:
                        key1:
                          type: string
                          example: "value1"
                      description: "Partner-specific metadata"

      responses:
        '200':
          description: ''
          headers: { }
      deprecated: false
  /registered_url_for_prescription_events:
    post:
      tags:
        - Prescription Webhooks
      summary: Prescription Events
      description: >-
        
        When a prescription is created or modified, a webhook event is sent to registered webhooks with details about the prescription, including the prescription ID, visit ID, doctor ID, patient ID, and event type.
        
        
        The receiver can then use the `prescription_id` from webhook events to retrieve the details of a specific prescription by calling the prescription API.

      operationId: PrescriptionWebhook
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              required:
                - event
                - event_time
                - timestamp
                - client_id
                - business_id
                - data
              properties:
                event:
                  type: string
                  enum:
                    - "prescription.created"
                    - "prescription.updated"
                event_time:
                  type: integer
                  example: 1730189586
                  description: "Event occured timestamp"
                timestamp:
                  type: integer
                  example: 1730189586
                  description: "Timestamp of the event"
                client_id:
                  type: string
                  example: "{{client_id}}"
                  description: "Client ID for the appointment"
                business_id:
                  type: string
                  example: "{{business_id}}"
                  description: "Business ID for the appointment"
                data:
                  type: object
                  required:
                    - prescription_id
                    - doctor_id
                    - patient_id
                    - clinic_id
                    - action
                    - created_at
                    - modified_at
                  properties:
                    prescription_id:
                      type: string
                      example: "{{prescription_id}}"
                      description: "Prescription ID"
                    doctor_id:
                      type: string
                      example: "{{doctor_id}}"
                      description: "Identifier for the doctor in Eka"
                    partner_doctor_id:
                      type: string
                      example: "{{partner_doctor_id}}"
                      description: "Identifier for the partner's doctor"
                    patient_id:
                      type: string
                      example: "{{patient_id}}"
                      description: "Identifier for the patient in Eka"
                    prescription_version:
                      type: string
                      example : 1
                    partner_patient_id:
                      type: string
                      example: "{{partner_patient_id}}"
                      description: "Identifier for the partner's patient"
                    clinic_id:
                      type: string
                      example: "{{clinic_id}}"
                      description: "Identifier for the clinic in Eka"
                    partner_clinic_id:
                      type: string
                      example: "{{partner_clinic_id}}"
                      description: "Identifier for the partner's clinic"
                    partner_appointment_id:
                      type: string
                      example: "{{partner_appointment_id}}"
                      description: "Identifier for the partner's appointment"
                    action:
                      type: string
                      enum:
                        - "created"
                        - "updated"
                    created_at:
                      type: integer
                      example: 1730189586
                      description: "Creation timestamp in ISO format"
                    modified_at:
                      type: integer
                      example: 1730189586
                      description: "Modification timestamp in ISO format"
                    partner_meta:
                      type: object
                      properties:
                        key1:
                          type: string
                          example: "{{value1}}"
                          description: "key-value specified by partner"
                      description: "Partner-specific metadata"
                    
      responses:
        '200':
          description: ''
          headers: { }
      deprecated: false
  /registered_url_for_doctor_events:
    post:
      tags:
        - Doctor Webhooks
      summary: Doctor Events
      description: >-
        When a Doctor event occurs (such as the start of a practice), a webhook event is sent to registered webhooks with details about the schedule, including the doctor ID, partner doctor ID, and event time.
      
        The receiver can use the details from the webhook event to update or manage schedules in the system.
      operationId: ScheduleStartPracticeWebhook
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              required:
                - event
                - event_time
                - timestamp
                - client_id
                - business_id
                - data
              properties:
                event:
                  type: string
                  enum:
                    - "schedule.start_practice"
                    - "schedule.stop_practice"
                    - "schedule.available_for_consultation"
                  example: "schedule.start_practice"
                  description: "Type of event"
                event_time:
                  type: integer
                  example: 1730189586
                  description: "Event occurred timestamp"
                timestamp:
                  type: integer
                  example: 1730189586
                  description: "Timestamp of the event"
                client_id:
                  type: string
                  example: "{{client_id}}"
                  description: "Client ID for the schedule"
                business_id:
                  type: string
                  example: "{{business_id}}"
                  description: "Business ID for the schedule"
                data:
                  type: object
                  required:
                    - doctor_id
                    - partner_doctor_id
                    - created_at
                    - modified_at
                  properties:
                    doctor_id:
                      type: string
                      example: "{{doctor_id}}"
                      description: "Identifier for the respective doctor in Eka"
                    partner_doctor_id:
                      type: string
                      example: "{{partner_doctor_id}}"
                      description: "Identifier for the partner’s respective doctor"
                    clinic_id:
                      type: string
                      example: "{{clinic_id}}"
                      description: "Identifier for the respective clinic in eka"
                    partner_clinic_id:
                      type: string
                      example: "{{partner_clinic_id}}"
                      description: "Identifier for the partner’s respective clinic"
                    created_at:
                      type: integer
                      example: 1730189586
                      description: "Creation timestamp in ISO format"
                    modified_at:
                      type: integer
                      example: 1730189586
                      description: "Modification timestamp in ISO format"
                    partner_meta:
                      type: object
                      properties:
                        key1:
                          type: string
                          example: "value1"
                          description: "Partner-specific metadata"
                      description: "Partner-specific metadata"
      responses:
        '200':
          description: "Successfully received the schedule event"
          headers: {}
      deprecated: false
