openapi: 3.1.0
info:
  title: Webhook Service for the Connect Clients
  description: |
    The Webhook Service allows clients to register webhooks that are triggered based on specific events. Each webhook is associated with a business_id, connect_id, url, and a scope. The scope defines the type of events that will trigger the webhook.
  version: 1.0.0
servers:
  - url: https://api.eka.care
components:
  securitySchemes:
    auth:
      type: apiKey
      in: header
      name: auth
      description: |
        The API requires the following auth in headers for authentication.
  schemas:
    RegisterWebhookRequest:
      type: object
      properties:
        scope:
          type: string
          description: Enum - All, Appointment, SA
        url:
          type: string
        secret:
          type: string
        c-id:
          type: string
          description: c-id will only come here in hub.eka.care caller case
      required:
        - scope
        - url
        - secret
    WebhookResponse:
      type: object
      properties:
        id:
          type: integer
        business_id:
          type: string
        scope:
          type: string
        url:
          type: string
        secret:
          type: string
          nullable: true
        connect_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        created_by:
          type: string
        updated_by:
          type: string
    UpdateWebhookRequest:
      type: object
      properties:
        secret:
          type: string
        url:
          type: string
      required:
        - secret
        - url
paths:
  /notification/v1/connect/webhook/subscriptions:
    post:
      tags:
        - Webhooks
      summary: Register Webhook
      description: Registers a new webhook.
      security:
        - auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterWebhookRequest'
      responses:
        '201':
          description: Webhook registered successfully.
        '400':
          description: Invalid input data.
        '500':
          description: Server error.
    get:
      tags:
        - Webhooks
      summary: Get Webhooks
      description: Retrieves all registered webhooks.
      security:
        - auth: []
      responses:
        '200':
          description: List of webhooks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebhookResponse'

  /notification/v1/connect/webhook/subscriptions/{id}:
    put:
      tags:
        - Webhooks
      summary: Update Webhook
      description: Updates an existing webhook's URL or event type based on its ID.
      security:
        - auth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWebhookRequest'
      responses:
        '200':
          description: Webhook updated successfully.
        '400':
          description: Invalid request.
        '404':
          description: Webhook not found.
        '500':
          description: Server error.
    delete:
      tags:
        - Webhooks
      summary: Delete Webhook
      description: Deletes a webhook by ID.
      security:
        - auth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Webhook deleted successfully.
        '404':
          description: Webhook not found.
        '500':
          description: Server error.