openapi: 3.1.0
info:
  title: Notification Connect
  version: 1.0.0
servers:
  - url: https://api.eka.care
components:
  securitySchemes:
    auth:
      type: apiKey
      in: header
      name: auth
      description: |
        The API requires the following auth in headers for authentication.
paths:
  /notification/v1/notify:
    post:
      tags:
        - Notifications
      summary: Send Notification
      description: This API allows partners to send notifications to users. The notifications can include a title, body, image URL, link, and a param if provided. The API supports different platform flavors such as Android, iOS, iPad and Web.
      security:
        - auth: [ ]
      operationId: sendNotification
      requestBody:
        description: Notification payload
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - partner_doctor_id
                - message
                - landing_page
              properties:
                partner_doctor_id:
                  type: string
                  example: "test-p1"
                  description: "The unique partner ID for the business."
                message:
                  type: object
                  required:
                    - title
                    - body
                  properties:
                    title:
                      type: string
                      example: "test title"
                      description: "The title of the notification."
                    body:
                      type: string
                      example: "test body"
                      description: "The content that should be displayed in the notification."
                    img:
                      type: string
                      example: "img url"
                      description: "The image URL for the notification."
                landing_page:
                  type: string
                  enum:
                    - "h"
                    - "q"
                    - "p"
                  example: "q"
                  description: |-
                    The page where the user should land upon opening the notification.
                    - "h" is for homepage.
                    - "q" is for appointments queue.
                    - "p" is for patient directory.
                params:
                  type: object
                  example:
                    action: "move"
                    aid: "12345"
                    status: "confirmed"
                  description: |-
                    Additional parameters to be added to the link for navigation, if provided.
                    Required for appointments ("a"), not required for homepage ("h") and patient directory ("p").
                    Here are some of the samples:
                    - Move appointment:
                      ```json
                      {
                        "action": "move",
                        "aid": "<appointment id>",
                        "status": "<status to be set on appointment>",
                      }
                      ```
                    - Book slot:
                      ```json
                      {
                        "action": "book-slot",
                        "patientOid": "<patient oid>"
                      }
                      ```
                    - Create appointment and bill patients:
                      ```json
                      {
                        "action": "create-appointment-and-bill-patient",
                        "patientOid": "<patient oid>"
                      }
                      ```
                flavour:
                  type: string
                  enum:
                    - "android"
                    - "ios"
                    - "ipad"
                    - "web"
                  example: "android"
                  description: "The platform on which the notification is allowed."
      responses:
        '200':
          description: Notification sent successfully.
        '400':
          description: Bad request.
        '500':
          description: Internal server error.