openapi: 3.1.0
info:
  title: Notification Connect
  description: |-
    | **Pipeline** | **Release Date** |
    | --- | --- |
    | Registration API | 12th Aug, 2024 |
  version: 1.0.0
servers:
  - url: https://api.eka.care
  - url: https://api.dev.eka.care
security:
  - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: auth
      in: header
  schemas:
    AddDeviceRequest:
      type: object
      properties:
        devicePayload:
          app-id:
            type: string
          app-platform:
            type: string
          app-version:
            type: string
          did:
            type: string
          fcm-id:
            type: string
          fid:
            type: string
          lang:
            type: string
          os-version:
            type: string
          user-hash:
            type: string
      example:
        devicePayload:
          app-id: 123
          app-platform: android
          app-version: 1.0.0
          did: 123
          fcm-id: 123
          fid: 123
          lang: en
          os-version: 1.0.0
          user-hash: 123
    FCMPayload:
      type: object
      properties:
        sa_key:
          type:
            type: string
          project_id:
            type: string
          private_key_id:
            type: string
          private_key:
            type: string
          client_email:
            type: string
          client_id:
            type: string
          auth_uri:
            type: string
          token_uri:
            type: string
          auth_provider_x509_cert_url:
            type: string
          client_x509_cert_url:
            type: string
          universal_domain:
            type: string
      example:
        sa_key:
          type: service_account
          project_id: example-project
          private_key_id: 1234567890abcdef
          private_key: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASC...\n-----END PRIVATE KEY-----\n
          client_email: example@example.iam.gserviceaccount.com
          client_id: 12345678901234567890
          auth_uri: https://accounts.google.com/o/oauth2/auth
          token_uri: https://oauth2.googleapis.com/token
          auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
          client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/example@example.iam.gserviceaccount.com
          universal_domain: example.com
paths:
  /notification/add-device:
    post:
      tags:
        - Notifications
      summary: Add Device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddDeviceRequest'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                success: true
  /notification/delete-device:
    delete:
      tags:
        - Notifications
      summary: Delete Device
      parameters:
        - name: device-id
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                success: true
  /notification/fcm-creds:
    post:
      operationId: addFcmCreds
      tags:
        - Notifications
      summary: Add FCM Credentials
      description: Store FCM credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FCMPayload'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: FCM token added successfully