openapi: 3.0.3
info:
  title: Assessment APIs
  version: 1.0.0
servers:
  - url: https://api.eka.care

paths:
  /assessments/init/:
    post:
      tags:
        - Assessments > Initialization
      summary: Initialize the assessments
      description: >-
        This API is used to initialize the assessment. It returns the hash that is used to continue the assessment.
        <Warning>This API must be called before starting the assessment</Warning>

      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_info:
                  dob: '2001-01-01'
                  gender: M
              description: >-
                The request body must contain the user information.
                The format should be:


                ```json

                {
                  "user_info": {
                    "dob": "YYYY-MM-DD",
                    "gender": "M"/"F"
                  }
                }

      parameters:
        - name: locale
          in: header
          description: >-
            The locale of the user. It is used to determine the language of the assessment.
          schema:
            type: string
          example: en
        - name: auth
          in: header
          description: >-
            The auth token of the user. It is used to authenticate the user.
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJiX2lkIjoiMTIzNDU2IiwiY2xpZW50X2lkIjoiNzg5MCIsImV4dHJhX2ZpZWxkIjoiZXh0cmFfZmllbGRfZGF0YSJ9.q9KzBI6f4l3OyM_EkB5Quq0l9EEMFh5JS-fx3F_PHUM
        - name: Content-Type
          in: header
          description: >-
            The content type of the request. It is used to determine the type of data being sent.
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Mon, 12 Aug 2024 07:41:05 GMT
            Server:
              schema:
                type: number
                example: WSGIServer/0.2 CPython/3.9.17
            Content-Type:
              schema:
                type: string
                example: application/json
            Vary:
              schema:
                type: string
                example: Accept, Cookie, origin
            Allow:
              schema:
                type: string
                example: POST, OPTIONS
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Length:
              schema:
                type: integer
                example: '51'
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Referrer-Policy:
              schema:
                type: string
                example: same-origin
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  init_hash: sn_1212121212
        '400':
          description: Bad Request
          headers:
            Date:
              schema:
                type: string
                example: Mon, 12 Aug 2024 07:41:05 GMT
            Server:
              schema:
                type: number
                example: WSGIServer/0.2 CPython/3.9.17
            Content-Type:
              schema:
                type: string
                example: application/json
            Vary:
              schema:
                type: string
                example: Accept, Cookie, origin
            Allow:
              schema:
                type: string
                example: POST, OPTIONS
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Length:
              schema:
                type: integer
                example: '51'
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Referrer-Policy:
              schema:
                type: string
                example: same-origin
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
          content:
            application/json:
              schema:
                type: object
              example:
                error:
                  - error_code: missing_field
                    message:
                      user_info:
                        gender:
                          - This field may not be null.
  