openapi: 3.0.3
info:
  title: Assessment APIs
  version: 1.0.0
servers:
  - url: https://api.eka.care

paths:
  /assessment/api/v1/init/:
    post:
      tags:
        - Assessments > Initialization
      summary: Initialization
      description: >-
        This API is used to initialize the assessment. It returns the hash that is used to continue the assessment.
        <Warning>This API must be called before starting the assessment</Warning>

      requestBody:
        description: The request body must contain the user informationnnnnn.
        content:
          application/json:
            schema:
              type: object
              example:
                user_info:
                  dob: '2001-01-01'
                  gender: M
              description: >-
                The request body must contain the user information.


                Users can either provide the date of birth or age using `dob` and `age` fields respectively inside `user_info`.
                The format should be:

                ```json

                {
                  "user_info": {
                    "dob": "YYYY-MM-DD",
                    "gender": "M"/"F"
                  }
                }


      parameters:
        - name: auth
          in: header
          required: True
          description: >-
            The auth token of the user. It is used to authenticate the user.
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJiX2lkIjoiMTIzNDU2IiwiY2xpZW50X2lkIjoiNzg5MCIsImV4dHJhX2ZpZWxkIjoiZXh0cmFfZmllbGRfZGF0YSJ9.q9KzBI6f4l3OyM_EkB5Quq0l9EEMFh5JS-fx3F_PHUM
        - name: client_id
          in: header
          required: True
          description: >-
            The client id of the user. It is used to identify the user.
          schema:
            type: string
          example: application/json
        - name: locale
          in: header
          description: >-
            The locale of the user. It is used to determine the language of the assessment. Supported locales are `en`, `hi`, `kn` for english, hindi and kannada respectively. Default value is `en`.
          schema:
            type: string
          example: en
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  init_hash: sn_1212121212
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                error:
                  error_code: unique_error_code
                  display_message: Display message for the user
                  message: Actual error message from the server
